name: CI-CD Pipline

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

permissions:
  actions: read

jobs:
  build:
    name: Develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout Go
        uses: actions/checkout@v4
        with:
          go-version: "1.23"
        id: go

      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"  

      - name: Install project dependenies
        run:  pwd && go mod tidy  

      - name: Build
        run: pwd && go build -v ./...

      - name: Test
        run: go test -v ./...    